# Generated by Django 4.0.6 on 2022-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('product_desc', models.CharField(default='', max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_category', models.CharField(default='', max_length=200)),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
